version: "2"
services:
  elastic:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana
    ports:
      - 5601:5601
    links:
      - elastic:elasticsearch
